app:
  title: "Fabric Comfort AI Recommender"
  theme_color: "#2563EB"

data:
  dataset1: "https://raw.githubusercontent.com/Volandofernando/Material-Literature-data-/main/Dataset.xlsx"
  dataset2: "https://raw.githubusercontent.com/Volandofernando/REAL-TIME-Dataset/main/IT%20Innovation%20in%20Fabric%20Industry%20%20(Responses).xlsx"

ml:
  features: ["Thermal_Resistance", "Air_Permeability", "Moisture_Regain", "Thickness"]
  target: "Comfort_Score"
  n_estimators: 200
