app:
  title: "AI Fabric Recommender"
  subtitle: "Dissertation Project — University of West London"
  theme_color: "#2E86C1"

dataset:
  path: "data/Dataset.xlsx"
  sheet_name: "Sheet1"

features:
  - moisture_regain_
  - water_absorption_g_m2_
  - drying_time_min_
  - thermal_conductivity_w_m_k_

target: comfort_score_l_10_
