app:
  title: "AI Fabric Recommender"
  subtitle: "Dissertation Project — University of West London"
  theme_color: "#2E86C1"

datasets:
  literature_url: "https://raw.githubusercontent.com/Volandofernando/Material-Literature-data-/main/Dataset.xlsx"
  survey_url: "https://raw.githubusercontent.com/Volandofernando/REAL-TIME-Dataset/main/IT%20Innovation%20in%20Fabric%20Industry%20%20(Responses).xlsx"


features:
  - moisture_regain_
  - water_absorption_g_m2_
  - drying_time_min_
  - thermal_conductivity_w_m_k_

target: comfort_score_l_10_
