app:
  title: "Fabric Comfort Recommender"
  theme_color: "#2563EB"

data:
  dataset1: "data/Dataset.xlsx"
  dataset2: "data/IT Innovation in Fabric Industry.xlsx"

ml:
  features: ["Thermal_Resistance", "Air_Permeability", "Moisture_Regain", "Thickness"]
  target: "Comfort_Score"
  n_estimators: 200
