app:
  title: "Fabric Comfort AI Recommender"
  theme_color: "#2563EB"

data:
  path: "https://github.com/Volandofernando/REAL-TIME-Dataset/blob/main/IT%20Innovation%20in%20Fabric%20Industry%20%20(Responses).xlsx",
  "https://github.com/Volandofernando/Material-Literature-data-/blob/main/Dataset.xlsx" # <-- put your dataset here
  target: "comfort_score"
  features:
    - absorption_rate
    - drying_time
    - thermal_conductivity
    - air_permeability
    - gsm
    - price
    - sustainability_score

model:
  test_size: 0.2
  random_state: 42
  params:
    n_estimators: 250
    max_depth: 12
